Integrated the latest start up script from the FreeBSD ports collection

diff --git a/extra/samba/samba.in b/extra/samba/samba.in
--- a/extra/samba/samba.in
+++ b/extra/samba/samba.in
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $FreeBSD: net/samba4/files/samba4.in 322565 2013-07-09 15:30:00Z timur $
+# $FreeBSD: head/net/samba41/files/samba_server.in 379838 2015-02-24 20:44:10Z timur $
 #
 
 # PROVIDE: samba4
@@ -13,6 +13,12 @@
 #
 #samba4_enable="YES"
 #
+# You can disable/enable any of the Samba daemons by specifying:
+#samba_enable="NO"
+#nmbd_enable="NO"
+#smbd_enable="NO"
+# You need to enable winbindd separately, by adding:
+#winbindd_enable="YES"
 # Configuration file can be set with:
 #samba4_config="%%SAMBA4_CONFDIR%%/%%SAMBA4_CONFIG%%"
 #
@@ -21,31 +27,20 @@
 
 name="samba4"
 rcvar=${name}_enable
-
-load_rc_config "${name}"
-
 # Defaults
-samba4_enable=${samba4_enable:=NO}
-samba4_flags=${samba4_flags=--daemon}
 samba4_config_default="%%SAMBA4_CONFDIR%%/%%SAMBA4_CONFIG%%"
-samba4_config=${samba4_config=${samba4_config_default}}
-samba4_configfile_arg=${samba4_config:+--configfile="${samba4_config}"}			#"
-testparm_command="/usr/bin/testparm --suppress-prompt --verbose ${samba4_configfile_arg}"
-# Fetch parameters from configuration file
-samba4_role=$(${testparm_command} --parameter-name='server role' 2>/dev/null)
-samba4_lockdir=$(${testparm_command} --parameter-name='lock directory' 2>/dev/null)
-samba4_piddir=$(${testparm_command} --parameter-name='pid directory' 2>/dev/null)
+smbcontrol_command="%%PREFIX%%/bin/smbcontrol"
+# Custom commands
+extra_commands="reload status"
 
-# Runtime options
 start_precmd="samba4_prestart"
 restart_precmd="samba4_checkconfig"
-command_name="samba"
-command="/usr/sbin/${command_name}"
-command_args=${samba4_configfile_arg}
-pidfile="/var/run/samba/${command_name}.pid"
-# Requirements
-required_files="${samba4_config}"
-required_dirs="${samba4_lockdir}"
+reload_precmd="samba4_checkconfig"
+start_cmd="samba4_cmd"
+stop_cmd="samba4_cmd"
+status_cmd="samba4_cmd"
+reload_cmd="samba4_reload_cmd"
+rcvar_cmd="samba4_rcvar_cmd"
 
 samba4_checkconfig() {
     echo -n "Performing sanity check on Samba configuration: "
@@ -62,10 +57,140 @@ samba4_prestart() {
     if [ ! -d "${samba4_piddir}" -a ! -e "${samba4_piddir}" ]; then
 	install -m 0755 -d "${samba4_piddir}"
     fi
-    # Remove smbd.pid before starting up samba(needed for s3fs)
-    if [ -e "${samba4_piddir}/smbd.pid" ] ; then
-	rm -f "${samba4_piddir}/smbd.pid"
-    fi
+#    # Remove smbd.pid before starting up samba(needed for s3fs)
+#    if [ -e "${samba4_piddir}/smbd.pid" ] ; then
+#	rm -f "${samba4_piddir}/smbd.pid"
+#    fi
+    samba4_checkconfig
 }
+
+samba4_rcvar_cmd() {
+    local name rcvar
+    rcvar=${name}_enable
+    # Prevent recursive calling
+    unset "${rc_arg}_cmd" "${rc_arg}_precmd" "${rc_arg}_postcmd"
+    # Check master variable
+    run_rc_command "${_rc_prefix}${rc_arg}" ${rc_extra_args}
+    # Check dependent variables
+    for name in ${samba_daemons}; do
+	# XXX
+	rcvars=''; v=''
+	rcvar=${name}_enable
+	run_rc_command "${_rc_prefix}${rc_arg}" ${rc_extra_args}
+    done
+}
+
+samba4_reload_cmd() {
+    local name rcvar command pidfile force_run
+    # Prevent recursive calling
+    unset "${rc_arg}_cmd" "${rc_arg}_precmd" "${rc_arg}_postcmd"
+    # Ignore rcvar and run command
+    if [ -n "${_rc_prefix}" -a "${_rc_prefix}" = "one" ] || [ -n "${rc_force}" ] || [ -n "${rc_fast}" ]; then
+	force_run=yes
+    fi
+    # Apply to all daemons
+    for name in ${samba_daemons}; do
+	rcvar=${name}_enable
+	command="%%PREFIX%%/sbin/${name}"
+	pidfile="${samba4_piddir}/${name}.pid"
+	# Daemon should be enabled and running
+	if ( [ -n "${rcvar}" ] && checkyesno "${rcvar}" ) || [ -n "$force_run" ]; then
+	    if [ -n "$(check_pidfile "${pidfile}" "${command}")" ]; then
+		debug "reloading ${name} configuration"
+		echo "Reloading ${name}."
+		${smbcontrol_command} "${name}" 'reload-config' ${command_args} >/dev/null 2>&1
+	    fi
+	fi
+    done
+}
+
+samba4_cmd() {
+    local name rcvar rcvars v command pidfile samba_daemons result force_run
+    # Prevent recursive calling
+    unset "${rc_arg}_cmd" "${rc_arg}_precmd" "${rc_arg}_postcmd"
+    # Stop processes in the reverse order
+    if [ "${rc_arg}" = "stop" ] ; then
+	samba_daemons=$(reverse_list ${samba_daemons})
+    fi
+    # Ignore rcvar and run command
+    if [ -n "${_rc_prefix}" -a "${_rc_prefix}" = "one" ] || [ -n "${rc_force}" ] || [ -n "${rc_fast}" ]; then
+	force_run=yes
+    fi
+    # Assume success
+    result=0
+    # Apply to all daemons
+    for name in ${samba_daemons}; do
+	# XXX
+	rcvars=''; v=''
+	rcvar=${name}_enable
+	command="%%PREFIX%%/sbin/${name}"
+	pidfile="${samba4_piddir}/${name}.pid"
+	# Daemon should be enabled and running
+	if ( [ -n "${rcvar}" ] && checkyesno "${rcvar}" ) || [ -n "$force_run" ]; then
+	    run_rc_command "${_rc_prefix}${rc_arg}" ${rc_extra_args}
+	    # If any of the commands failed, take it as a global result
+	    result=$((${result} || $?))
+	fi
+    done
+    return ${result}
+}
+
+samba4_config_init() {
+    local name
+    # Load configuration
+    load_rc_config "${name}"
+    # Defaults
+    samba4_enable=${samba4_enable:=NO}
+    samba4_config=${samba4_config=${samba4_config_default}}
+    samba4_configfile_arg=${samba4_config:+--configfile="${samba4_config}"}			#"
+    #testparm_command="%%PREFIX%%/bin/samba-tool testparm --suppress-prompt --verbose ${samba4_configfile_arg}"
+    testparm_command="%%PREFIX%%/bin/testparm --suppress-prompt --verbose ${samba4_config}"
+    # Determine what daemons are necessary to run Samba in the current role
+    samba4_role=$(${testparm_command} --parameter-name='server role' 2>/dev/null)
+    case "${samba4_role}" in
+	active\ directory\ domain\ controller)
+	    samba_daemons="samba"
+	    ;;
+	auto|*)
+	    samba_daemons="nmbd smbd winbindd"
+	    ;;
+    esac
+    # Load daemons configuration
+    for name in ${samba_daemons}; do
+	load_rc_config "${name}"
+	# If samba4_enable is 'YES'
+	if [ -n "${rcvar}" ] && checkyesno "${rcvar}"; then
+	    if [ "${name}" != "winbindd" ]; then
+		# Set variable to 'YES' only if it is unset
+		eval ${name}_enable=\${${name}_enable-YES}
+	    else
+		# Winbindd
+		samba4_idmap=$(${testparm_command} --parameter-name='idmap uid' 2>/dev/null)
+		if [ -n "${samba4_idmap}" ]; then
+		    winbindd_enable="YES"
+		fi
+	    fi
+	fi
+	# If variable is empty, set it to 'NO'
+	eval ${name}_enable=\${${name}_enable:-NO}
+    done
+    # Fetch parameters from configuration file
+    samba4_lockdir="$(${testparm_command} --parameter-name='lock directory' 2>/dev/null)"
+    samba4_lockdir=${samba4_lockdir:=%%SAMBA4_LOCKDIR%%}
+    samba4_piddir="$(${testparm_command} --parameter-name='pid directory' 2>/dev/null)"
+    samba4_piddir=${samba4_piddir:=%%SAMBA4_RUNDIR%%}
+}
+
+# Load configuration variables
+samba4_config_init
+# Common flags
+command_args=${samba4_configfile_arg}
+samba_flags=${samba_flags="--daemon"}
+nmbd_flags=${nmbd_flags="--daemon"}
+smbd_flags=${smbd_flags="--daemon"}
+winbindd_flags=${winbindd_flags="--daemon"}
+# Requirements
+required_files="${samba4_config}"
+required_dirs="${samba4_lockdir}"
 
 run_rc_command "$1"
